<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="lenovo" name="reportSuiteA.TestA1" tests="3" failures="1" timestamp="1 Oct 2016 18:19:22 GMT" time="0.009" errors="1">
  <testcase name="testA1_2" time="0.002" classname="reportSuiteA.TestA1">
    <failure type="java.lang.AssertionError" message="Faliure Message">
      <![CDATA[java.lang.AssertionError: Faliure Message
	at org.testng.Assert.fail(Assert.java:89)
	at reportSuiteA.TestA1.testA1_2(TestA1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1031)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1027)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:956)
	at org.testng.TestNG.run(TestNG.java:892)
	at org.testng.TestNG.privateMain(TestNG.java:1174)
	at org.testng.TestNG.main(TestNG.java:1138)
]]>
    </failure>
  </testcase>
  <testcase name="testA1_1" time="0.007" classname="reportSuiteA.TestA1"/>
  <testcase name="testA1_3" time="0.000" classname="reportSuiteA.TestA1">
    <error type="org.testng.SkipException" message="Skipping test due to some failure">
      <![CDATA[org.testng.SkipException: Skipping test due to some failure
	at reportSuiteA.TestA1.testA1_3(TestA1.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1031)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1027)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:956)
	at org.testng.TestNG.run(TestNG.java:892)
	at org.testng.TestNG.privateMain(TestNG.java:1174)
	at org.testng.TestNG.main(TestNG.java:1138)
]]>
    </error>
  </testcase>
</testsuite>
